In [1]:
import numpy as np

In [4]:
a = np.array([1, 2, 3])
b = np.array([10, 20])

In [13]:
a[:, None] + b

array([[11, 21],
       [12, 22],
       [13, 23]])

In [7]:
m = np.array([[1, 2], [3, 4], [5, 6]])

In [14]:
a, m

(array([1, 2, 3]),
 array([[1, 2],
        [3, 4],
        [5, 6]]))

In [16]:
a.shape, m.shape

((3,), (3, 2))

In [18]:
np.matmul(a, m)

array([22, 28])

In [15]:
a @ m

array([22, 28])